// Message ordering and dedup for a real-time chat.
// One action, `server`, covers every way a confirmed message can arrive: the HTTP ack of our own
// send, the WebSocket echo/broadcast, a catch-up fetch after a reconnect, or a history page.
// Merging is idempotent, so delivery can be at-least-once and in any order.

export type MessageStatus = 'pending' | 'sent' | 'failed';

export type ChatMessage = {
  clientId: string; // generated by the sender; `srv:<id>` for other people's messages
  id: string | null; // server id, null until confirmed
  seq: number | null; // server-assigned, monotonic per room, null until confirmed
  author: string;
  text: string;
  status: MessageStatus;
};

export type ServerMessage = { id: string; seq: number; clientId?: string; author: string; text: string };

export type ChatState = {
  messages: readonly ChatMessage[]; // confirmed by seq, then unconfirmed in send order
  contiguousSeq: number; // every seq <= this is present
  gapAfter: number | null; // non-null: a hole exists, fetch messages with seq > gapAfter
};

export type ChatAction =
  | { type: 'send'; clientId: string; author: string; text: string }
  | { type: 'server'; message: ServerMessage }
  | { type: 'failed'; clientId: string }
  | { type: 'retry'; clientId: string };

/** `baseSeq` = the seq just before the oldest message we load (0 for a brand-new room). */
export function createChatState(baseSeq = 0): ChatState {
  return { messages: [], contiguousSeq: baseSeq, gapAfter: null };
}

function normalize(baseContiguous: number, messages: ChatMessage[]): ChatState {
  const confirmed = messages.filter((m) => m.seq !== null).sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0));
  const unconfirmed = messages.filter((m) => m.seq === null);
  let contiguousSeq = baseContiguous;
  for (const m of confirmed) if (m.seq === contiguousSeq + 1) contiguousSeq = m.seq;
  const last = confirmed[confirmed.length - 1];
  const gapAfter = last?.seq !== undefined && last.seq !== null && last.seq > contiguousSeq ? contiguousSeq : null;
  return { messages: [...confirmed, ...unconfirmed], contiguousSeq, gapAfter };
}

function setStatus(state: ChatState, clientId: string, from: MessageStatus, to: MessageStatus): ChatState {
  if (!state.messages.some((m) => m.clientId === clientId && m.status === from)) return state;
  return { ...state, messages: state.messages.map((m) => (m.clientId === clientId ? { ...m, status: to } : m)) };
}

export function chatReducer(state: ChatState, action: ChatAction): ChatState {
  switch (action.type) {
    case 'send': {
      if (state.messages.some((m) => m.clientId === action.clientId)) return state;
      const pending: ChatMessage = { clientId: action.clientId, id: null, seq: null, author: action.author, text: action.text, status: 'pending' };
      return { ...state, messages: [...state.messages, pending] };
    }
    case 'server': {
      const m = action.message;
      if (state.messages.some((x) => x.id === m.id)) return state; // duplicate delivery: no-op, same reference
      const confirmed: ChatMessage = { clientId: m.clientId ?? `srv:${m.id}`, id: m.id, seq: m.seq, author: m.author, text: m.text, status: 'sent' };
      const idx = m.clientId === undefined ? -1 : state.messages.findIndex((x) => x.clientId === m.clientId);
      const next = idx >= 0 ? state.messages.map((x, i) => (i === idx ? confirmed : x)) : [...state.messages, confirmed];
      return normalize(state.contiguousSeq, next);
    }
    case 'failed': // only a still-pending message can fail: an ack that already arrived wins
      return setStatus(state, action.clientId, 'pending', 'failed');
    case 'retry':
      return setStatus(state, action.clientId, 'failed', 'pending');
  }
}
